# Generated by Django 3.2.1 on 2021-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
    ]
